config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

posts/urls.py
from django.urls import path
from .views import (
        PostListView, 
        PostDetailView,
        PostCreateView,
)


urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('new/', PostCreateView.as_view(), name='new'),
]

pages/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=256)
    subtitle = models.CharField(max_length=256)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', args=[self.id])

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "pages/home.html"

class AboutPageView(TemplateView):
    template_name = "pages/about.html"

posts/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from .models import Post


class PostListView(ListView):
    template_name = "posts/list.html"
    model = Post


class PostDetailView(DetailView):
    template_name = "posts/detail.html"
    model = Post


class PostCreateView(CreateView):
    template_name = "posts/new.html"
    model = Post
    fields = ['title', 'subtitle', 'body']

    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <!-- CSS only -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid gap-5">
            <a class="navbar-brand" href="{% url 'home' %}">MarkIT Share</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link me-3" href="{% url 'home' %}">Home</a>
                <a class="nav-link me-3" href="{% url 'list' %}">Posts</a>
                <a class="nav-link me-3" href="{% url 'new' %}">New Post</a>
                <a class="nav-link me-3" href="{% url 'about' %}">About Me</a>
            </div>
            </div>
        </div>
    </nav>
    <div class="container">
    {% block content %}
    {% endblock content %}
    </div>
    <!-- JavaScript Bundle with Popper -->
    <script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
    </script>
</body>
</html>

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}


{% block title %}About{% endblock title %}

{% block content %}
<br>
<h2>About Me</h2>
<p>Hello everyone! My name is Seralvin Burgos. I am coming from an extensive career in emergency medicine during my 21 year career in the U.S. Air Force. I have decided to choose a different path and currently aspiring to become a Software Developer. I have an amazing wife, EJ, and two children, Nela and Aven.</p>
<br>
<div class="container-fluid">
    <div class="row mx-auto">
        <img class="" id="family" src="{% static 'img/wife.jpg' %}">
        <br>
        <img class="" id="family" src="{% static 'img/kids.jpg' %}">
    </div>
</div>
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}



{% block title %}Home{% endblock title %}

{% block content %}
<br>
<h1>Welcome to Markit Share</h1>
<br>
<h5>A place to post anything and everything on various topics. Feel free to express ideas and welcome thoughtful discussion.</h5>
<br>
<p>To get started, follow the links above to view any current posts or to start your own discussion.</p>
{% endblock content %}

templates/posts/detail.html
{% extends 'base.html' %}


{% block title %}{{ post.title }}{% endblock title %}


{% block content %}
<h1>{{ post.title }}</h1>
<h3>{{ post.subtitle }}</h3>
<small>Created on: {{ post.created_on }}</small>
<p>{{ post.body }}</p>
{% endblock content %}

templates/posts/list.html
{% extends 'base.html' %}



{% block title %}Posts{% endblock title %}

{% block content %}
<br>
<h1>Posts</h1>
<ul>
    {% for post in post_list %}
    <li>
        <a href="{% url 'detail' post.id %}">
            {{ post.title }}
        </a> 
    </li>
    {% endfor %}
</ul>
{% endblock content %}

templates/posts/new.html
{% extends 'base.html' %}



{% block title %}New Post{% endblock title %}

{% block content %}
<br>
<h1>New Post</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}